version: '2'
services:
    mysql: 
        image: "mysql:5.7"
        ports: 
            - 3306:3306
        environment: 
            - MYSQL_ROOT_PASSWORD=wy1015wy
        volumes: 
            - /docekr/mysql:/var/lib/mysql
            
    redis:
        image: redis
        ports:
            - 6379:6379
            
    nginx:
        image: nginx
        ports:
            - 80:80
        volumes:
            - /docker/nginx/html:/usr/share/nginx/html
            - /docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf nginx
            
    rabbitmq:
        image: rabbitmq
        ports:
            - 5671:5671
            - 5672:5672
            - 15672:15672
            - 15671:15671 
            - 25672:25672
        volumes:
            - /data/rabbitmq-data/:/var/rabbitmq/lib
            