version: '2'
services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=wy1015wy
    volumes:
      - /f/docker/mysql:/var/lib/mysql

  redis:
    image: redis
    ports:
      - 6379:6379

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - /f/docker/mongo/db:/data/db

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - /f/docker/nginx/html:/usr/share/nginx/html
      - /f/docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf

  rabbitmq:
    image:  rabbitmq:3-management
    ports:
      - 5671:5671
      - 5672:5672
      - 15672:15672
      - 15671:15671
      - 25672:25672
    volumes:
      - /f/docker/rabbitmq/data/:/var/rabbitmq/lib

  tomcat:
    image: tomcat
    ports:
      - 8081:8080
    volumes:
      - /f/docker/tomcat/webapps:/usr/local/tomcat/webapps
      - /f/docker/tomcat/logs:/usr/local/tomcat/logs

